### ISSUE TITLE
How Would we Bundle JS Hooks and Tailwind Config?

### ISSUE THREAD

**Issue by cyanff** [elixirlearners/compounds#48]

**Comment by calebgasser** [comment]
With the web hooks we have a couple options.
- Copy it next to the `app.js` like we're doing the components and have them import it and connect up the hooks
- Do the same as above, except instead of copying it have it be an npm package.

For the tailwind I'm not sure...we should first check tosee if there is a way to import our changes. If not, it might be a better option for us to just use plain css for any custom properties and like the hooks, copy it over and have them include it in thier `app.css`

**Comment by calebgasser** [comment]
With the web hooks we have a couple options.
- Copy it next to the `app.js` like we're doing the components and have them import it and connect up the hooks
- Do the same as above, except instead of copying it have it be an npm package.

For the tailwind I'm not sure...we should first check tosee if there is a way to import our changes. If not, it might be a better option for us to just use plain css for any custom properties and like the hooks, copy it over and have them include it in thier `app.css`

**Comment by faroutchris** [comment]
For tailwind, I believe we should create a plugin that can be imported and added as a one-liner in the users tailwind config.
```
plugins: [
   require("compounds/plugin"),
   ...
]
```

Not sure if we should copy it over to the vendor folder or use npm though

**Comment by che-122** [comment]
I think copying things over to the vendor folder is good enough as long as we keep our dependencies low.

I think we can update the library through hex and overwrite old versions of the files in the vendor folder + add an upgrade guide for any breaking changes
